### ISSUE TITLE
Cannot create devlopment environment

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/acme_diags#99]
I was trying to create a new conda development environment on acme1 following instructions:

https://acme-climate.github.io/acme_diags/docs/html/install-config-run.html

```
git clone https://github.com/ACME-Climate/acme_diags
conda env create -n acme_diags_dev -f acme_diags/conda/acme_diags_env.yml
Fetching package metadata ...............


NoPackagesFoundError: Package missing in current linux-64 channels: 
  - udunits2 2.2.23 0
```

**Comment by zshaheen** [comment]
Grab the latest code from master. You'll see that we changed the order of the channels in 535f538c4804ff6c7ccb5c731a00f92dd6ee4839. The problem was that there was a `2.2.17` in the `uvcdat` channel and it tried to get that (b/c `uvcdat` was ahead of `conda-forge`). The recipe specified `2.2.23`, which is in `conda-forge`, hence causing the error.

If it works for you, you can then close this issue.

**Comment by golaz** [comment]
It works, but I'm getting v1.5.3 of matplotlib.

**Comment by golaz** [comment]
Probably should have tried the `--copy` option. Will try again tomorrow.

**Comment by golaz** [comment]
Unfortunately, `--copy` option is not a valid option for 

`conda env create -f acme_diags/conda/acme_diags_env.yml`

**Comment by zshaheen** [comment]
As of now, all env issues are fixed. Even installing with `conda install` seems to work, but further testing is required to allow users to install via this.
